stages:
  - build
  - push
cache:
  key: ${CI_PROJECT_ID}
  paths:
    - .gradle/

variables:
  OWNER: telegram-sms
  REPO: telegram-sms


build_nightly:
  image: alvrme/alpine-android:android-35-jdk17
  stage: build
  retry: 2
  only:
    - nightly
  script:
    - apk --update --no-cache add git openssl bash curl wget
    - echo -n ${KEYSTORE} | base64 -d > app/keys.jks
    - git submodule update --init --recursive
    - export VERSION_CODE=${CI_PIPELINE_ID}
    - export VERSION_NAME=${CI_COMMIT_REF_NAME}-${CI_COMMIT_SHORT_SHA}
    - export GRADLE_USER_HOME=$(pwd)/.gradle && mkdir -p ${GRADLE_USER_HOME}
    - echo -e "org.gradle.jvmargs=-Xmx1536m\n org.gradle.parallel=true" >> ${GRADLE_USER_HOME}/gradle.properties
    - chmod +x ./gradlew
    - ./gradlew assembleRelease
    - wget https://github.com/tcnksm/ghr/releases/download/v0.17.0/ghr_v0.17.0_linux_amd64.tar.gz
    - tar -zxvf  ghr_v0.17.0_linux_amd64.tar.gz
    - git push --set-upstream https://${GITHUB_ACCESS_KEY}@github.com/${OWNER}/${REPO}.git HEAD:refs/heads/${CI_COMMIT_REF_NAME}
    - ghr_v0.17.0_linux_amd64/ghr -t "${GITHUB_ACCESS_KEY}" -u "${OWNER}" -r "${REPO}" -b "$(cat .reall/changelog.txt)" --prerelease "${CI_COMMIT_REF_NAME}-${CI_COMMIT_SHORT_SHA}-$(date "+%Y%m%d%H%M")" "./app/build/outputs/apk/release/"
  artifacts:
    paths:
      - app/build/outputs/apk/release/telegram-sms-nightly-${comCI_COMMIT_SHORT_SHAmitId}.apk
    expire_in: 1 week

build_release:
  image: alvrme/alpine-android:android-35-jdk17
  stage: build
  retry: 2
  only:
    - master
  script:
    - apk --update --no-cache add git openssl bash curl wget
    - echo -n ${KEYSTORE} | base64 -d > app/keys.jks
    - git submodule update --init --recursive
    - export VERSION_CODE=${CI_PIPELINE_ID}
    - export VERSION_NAME=${CI_COMMIT_REF_NAME}-${CI_COMMIT_SHORT_SHA}
    - export GRADLE_USER_HOME=$(pwd)/.gradle && mkdir -p ${GRADLE_USER_HOME}
    - echo -e "org.gradle.jvmargs=-Xmx1536m\n org.gradle.parallel=true" >> ${GRADLE_USER_HOME}/gradle.properties
    - chmod +x ./gradlew
    - ./gradlew app:copy_language_pack
    - ./gradlew assembleRelease
    - wget https://github.com/tcnksm/ghr/releases/download/v0.17.0/ghr_v0.17.0_linux_amd64.tar.gz
    - tar -zxvf  ghr_v0.17.0_linux_amd64.tar.gz
    - git push --set-upstream https://${GITHUB_ACCESS_KEY}@github.com/${OWNER}/${REPO}.git HEAD:refs/heads/${CI_COMMIT_REF_NAME}
    - ghr_v0.17.0_linux_amd64/ghr -t "${GITHUB_ACCESS_KEY}" -u "${OWNER}" -r "${REPO}" -b "$(cat .reall/changelog.txt)" --prerelease "${CI_COMMIT_REF_NAME}-${CI_COMMIT_SHORT_SHA}-$(date "+%Y%m%d%H%M")" "./app/build/outputs/apk/release/"
  artifacts:
    paths:
      - app/build/outputs/apk/release/telegram-sms-${comCI_COMMIT_SHORT_SHAmitId}.apk
    expire_in: 1 week
