stages:
    - build
    - deploy
    - play
cache:
    key: ${CI_PROJECT_ID}
    paths:
        - .gradle/

push_github:
    stage: deploy
    only:
        - nightly
    script:
        - git push -f --set-upstream https://${github_key}@github.com/telegram-sms/telegram-sms.git HEAD:refs/heads/$CI_COMMIT_REF_NAME

release_github:
    dependencies:
        - build
    only:
        - master
    stage: deploy
    script:
        - git push --set-upstream https://${github_key}@github.com/telegram-sms/telegram-sms.git HEAD:refs/heads/$CI_COMMIT_REF_NAME
        - /opt/github-release-upload.sh github_api_token=${github_key} owner=telegram-sms repo=telegram-sms tag=${CI_COMMIT_REF_NAME}-${CI_COMMIT_SHORT_SHA} filename="./app/build/outputs/apk/release/app-release.apk" pre_release="false"
        - git clone https://git.reallserver.cn/qwe7002/telegram-sms.wiki.git wiki
        - cd wiki
        - git push -f --set-upstream https://${github_key}@github.com/telegram-sms/telegram-sms.wiki.git HEAD:refs/heads/$CI_COMMIT_REF_NAME
build:
    image: preventis/docker-android-alpine:latest
    stage: build
    only:
        - master
    script:
        - curl https://keystore.reallserver.cn/android/telegram-sms/keys.jks  -o app/keys.jks -u gitlab:${key_store_passwd}
        - export GRADLE_USER_HOME=$(pwd)/.gradle
        - touch $(pwd)/.gradle/gradle.properties && echo "org.gradle.daemon=true" >> $(pwd)/.gradle/gradle.properties
        - echo -e "ext {\n appVersionCode = ${CI_PIPELINE_ID}\n appVersionName = \"${CI_COMMIT_REF_NAME}-${CI_COMMIT_SHORT_SHA}\"}" > ./app/version.gradle
        - echo -e "systemProp.http.nonProxyHosts=dl.google.com\n systemProp.http.proxyHost=192.168.3.8\n systemProp.http.proxyPort=1080\n systemProp.https.proxyHost=192.168.3.8\n systemProp.https.proxyPort=1080\n org.gradle.jvmargs=-Xmx1536m\n org.gradle.parallel=true\n android.enableJetifier=true\n android.useAndroidX=true" >> gradle.properties
        - chmod +x ./gradlew
        - ./gradlew assembleRelease
        #Todo upload version code
    artifacts:
        paths:
            - app/build/outputs/apk/release/app-release.apk
        expire_in: 1 week

