stages:
    - build
    - push
    - release
cache:
    key: ${CI_PROJECT_ID}
    paths:
        - .gradle/

variables:
    OWNER: telegram-sms
    REPO: telegram-sms
    KEYSTORE_SERVER: keystore.git.reallct.uk

release_github:
    stage: push
    only:
        - master
    script:
        - eval $(ssh-agent -s)
        - ssh-add - <<< $(curl https://${KEYSTORE_SERVER}/gitlab-sshkey/id_ecdsa -u gitlab:${key_store_passwd})
        - git push --set-upstream git@github.com:${OWNER}/${REPO}.git HEAD:refs/heads/${CI_COMMIT_REF_NAME}

release_nightly_github:
    stage: push
    only:
        - nightly
    script:
        - eval $(ssh-agent -s)
        - ssh-add - <<< $(curl https://${KEYSTORE_SERVER}/gitlab-sshkey/id_ecdsa -u gitlab:${key_store_passwd})
        - git push --set-upstream git@github.com:qwe7002/${REPO}.git HEAD:refs/heads/${CI_COMMIT_REF_NAME} -f

release_apk:
    stage: release
    dependencies:
        - build_release
    only:
        - master
    script:
        - curl https://${KEYSTORE_SERVER}/gitlab-sshkey/github-key.env -o .reall_network/github-key.env -u gitlab:${key_store_passwd}
        - . .reall_network/github-key.env
        - ghr -t "${GITHUB_ACCESS_KEY}" -u "${OWNER}" -r "${REPO}" -b "$(cat .reall_network/changelog.txt)" "${CI_COMMIT_REF_NAME}-${CI_COMMIT_SHORT_SHA}-$(date "+%Y%m%d%H%M")" "./app/build/outputs/apk/release/app-release.apk"

build_release:
    image: alvrme/alpine-android:android-30
    stage: build
    only:
        - master
    script:
        - sdkmanager --install "ndk;21.3.6528147" "cmake;3.10.2.4988404"
        - git submodule update --init --recursive
        - export VERSION_CODE=${CI_PIPELINE_ID}
        - export VERSION_NAME=${CI_COMMIT_REF_NAME}-${CI_COMMIT_SHORT_SHA}
        - wget https://${KEYSTORE_SERVER}/android/telegram-sms/keys.jks -O app/keys.jks --http-user=gitlab --http-passwd=${key_store_passwd}
        - wget https://${KEYSTORE_SERVER}/android/telegram-sms/keystore.env -O .reall_network/keystore.env --http-user=gitlab --http-passwd=${key_store_passwd}
        - . .reall_network/keystore.env
        - export GRADLE_USER_HOME=$(pwd)/.gradle && mkdir -p ${GRADLE_USER_HOME}
        - echo -e "org.gradle.jvmargs=-Xmx1536m\n org.gradle.parallel=true" >> ${GRADLE_USER_HOME}/gradle.properties
        - chmod +x ./gradlew
        - ./gradlew app:copy_language_pack && ./gradlew assembleRelease
    artifacts:
        paths:
            - app/build/outputs/apk/release/app-release.apk
        expire_in: 1 week
