name: Android User Build

on: [push]

jobs:
    build:

        runs-on: ubuntu-latest

        steps:
            -   uses: actions/checkout@v1
            -   name: set up JDK 1.8
                uses: actions/setup-java@v1
                with:
                    java-version: 1.8
            -   name: Setting up the system environment
                run: cp ./.github/workflows/github-action-only.jks ./app/keys.jks
            -   name: Build with Gradle
                run: export KEYSTORE_PASS=000000000 && export ALIAS_NAME="key0" && export ALIAS_PASS=111111111 && export VERSION_CODE=1 && export VERSION_NAME="GITHUB-${GITHUB_SHA}" && ./gradlew assembleRelease
            -   name: Upload artifact
                uses: actions/upload-artifact@master
                with:
                    name: telegram-sms
                    path: app/build/outputs/apk/release/app-release.apk


